export const REIMBURSABLE_STATUSES = ["Processed", "Funded", "Deposited", "Settled"];
export const CREDIT_PAID_STATUSES = ["Funded", "Deposited", "Settled"];
export const ORIGINAL_RETURNED_STATUSES = ["Returned", "NSF", "Cancelled", "Canceled", "Failed"];
export function duplicateReimbursementCents(creditStatus:string,items:{amountCents:number;originalStatus:string}[]) {
  if (!CREDIT_PAID_STATUSES.includes(creditStatus)) return 0;
  return items.filter(i=>ORIGINAL_RETURNED_STATUSES.includes(i.originalStatus)).reduce((sum,i)=>sum+i.amountCents,0);
}
export function reimbursementTerms(name:string,code:string,items:{transferUuid:string;amountCents:number;dueDate:Date|string}[]) {
 const total=items.reduce((s,i)=>s+i.amountCents,0);
 return `REIMBURSEMENT AND DUPLICATE PAYMENT AGREEMENT\n\nCompany: 770 Technology LLC, doing business as PennyLime\nCustomer: ${name}\nAccount reference: ${code}\nReimbursement: $${(total/100).toFixed(2)}\n\nIdentified original debits\n${items.map(i=>`${new Date(i.dueDate).toISOString().slice(0,10)} — $${(i.amountCents/100).toFixed(2)} — GoACH ${i.transferUuid}`).join("\n")}\n\n1. Reimbursement\nPennyLime agrees to reimburse the Customer the amount above for the identified debits, to the same bank account used for those debits. This reimbursement is not a new advance and does not reopen the rejected application or restart its canceled payment schedule. Processing time depends on the banking network. Signing this agreement does not mean that the reimbursement has already been sent or received.\n\n2. If an original debit returns\nIf an identified debit is returned unpaid, reversed, or credited back by the bank after PennyLime has also reimbursed that debit, the Customer agrees to repay only the resulting verified duplicate benefit. Recovery must not exceed the reimbursement actually received for that debit, less any amount already repaid or recovered. No additional fee, interest, or penalty applies under this agreement.\n\n3. Notice and recovery\nBefore requesting repayment, PennyLime will provide the original transaction reference, evidence of the reimbursement and the bank return or credit, and an itemized calculation. The Customer may question the calculation and provide bank records. The parties will confirm the repayment date and method. This agreement alone does not authorize an automatic ACH debit; any such debit requires a separate, specific authorization identifying its amount, date, and account. The original canceled payment schedule will not be used for recovery.\n\n4. Preserved rights\nThis agreement does not waive the Customer’s rights to report or dispute a banking error or unauthorized transfer, or any other rights provided by law. PennyLime will not recover the same amount twice.`;
}
