"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {prepareReimbursement,sendReimbursementAgreement,sendReimbursementCredit,refreshReimbursement} from "@/actions/reimbursements";
type Account={id:string;name:string;code:string;status:string;payments:{id:string;amount:number;date:string;status:string;reserved:boolean}[]};
type Row={id:string;status:string;amount:number;text:string;hash:string;signedName:string|null;signedAt:string|null;sentAt:string|null;creditStatus:string|null;creditUuid:string|null;duplicate:number;lastError:string|null;items:{date:string;amount:number;status:string;reference:string}[]};
const money=(n:number)=>n.toLocaleString("en-US",{style:"currency",currency:"USD"});
export function ReimbursementManager({account:a,rows}:{account:Account;rows:Row[]}){
 const router=useRouter();const [selected,setSelected]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");
 async function run(fn:()=>Promise<{ok:boolean;error?:string}>,message:string){if(busy)return;setBusy(true);setNotice("");try{const r=await fn();if(!r.ok)setNotice(r.error||"Action failed.");else{setNotice(message);setSelected([]);router.refresh();}}catch{setNotice("Could not confirm the result. Refresh before retrying; do not submit a second reimbursement.");}finally{setBusy(false);}}
 const button="rounded-lg border px-4 py-2 text-sm font-semibold disabled:opacity-40";
 return <section className="space-y-4 rounded-xl border bg-white p-5"><div><h2 className="text-xl font-bold">{a.name}</h2><p className="text-sm text-zinc-500">{a.code} · {a.status}</p></div>{notice&&<p role="status" className="rounded-lg bg-amber-50 p-3 text-sm">{notice}</p>}
 {rows.map(r=><article key={r.id} className="space-y-4 rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{money(r.amount)} reimbursement</strong><span>{r.status}</span></div><details open={r.status==="DRAFT"}><summary className="cursor-pointer font-semibold text-green-700">Preview exact customer agreement</summary><pre className="mt-3 whitespace-pre-wrap font-sans text-sm leading-6">{r.text}</pre></details><p className="text-xs text-zinc-500">{r.signedAt?`Signed by ${r.signedName} · ${new Date(r.signedAt).toLocaleString()}`:r.sentAt?"Agreement sent — awaiting signature":"Draft only — nothing sent"}</p>
 <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Original payment</th><th>Amount</th><th>Processor status</th></tr></thead><tbody>{r.items.map(i=><tr key={i.reference}><td className="py-2">{i.date}<span className="block text-xs text-zinc-400">{i.reference}</span></td><td>{money(i.amount)}</td><td>{i.status}</td></tr>)}</tbody></table></div>
 {r.creditUuid&&<p className="text-sm">Reimbursement credit: {r.creditStatus} · {r.creditUuid}</p>}{r.lastError&&<p className="text-sm text-red-700">{r.lastError}</p>}
 {r.duplicate>0&&<p className="rounded-lg bg-amber-50 p-3 text-sm">Potential duplicate benefit: {money(r.duplicate)}. Verify bank evidence and subtract any amount already recovered before contacting the client. No fee. No automatic debit is authorized.</p>}
 <div className="flex flex-wrap gap-2">{["DRAFT","SENT"].includes(r.status)&&<button disabled={busy} className={button} onClick={()=>{if(confirm(`Send the ${money(r.amount)} reimbursement agreement to ${a.name}? This does not send money.`))void run(()=>sendReimbursementAgreement(r.id),"Agreement sent for signature. No money sent.");}}>{r.sentAt?"Resend agreement":"Send agreement for signature"}</button>}
 {r.status==="SIGNED"&&<button disabled={busy} className={button+" bg-green-700 text-white"} onClick={()=>{if(confirm(`Send ${money(r.amount)} to ${a.name}'s original payment bank account? This sends real money. Some original debits may still be processing.`))void run(()=>sendReimbursementCredit(r.id,true),"Reimbursement submitted. Refresh status to track delivery.");}}>Send reimbursement {money(r.amount)}</button>}
 <button disabled={busy} className={button} onClick={()=>run(()=>refreshReimbursement(r.id),"Processor statuses refreshed. No money moved.")}>Refresh processor status</button></div></article>)}
 <details><summary className="cursor-pointer font-semibold text-green-700">Prepare a reimbursement agreement</summary><p className="my-3 text-sm text-zinc-500">Select original debits. Their current status, amount, and bank destination will be checked with GoACH before preparing the agreement. Maximum $1,000 per agreement.</p>{a.payments.map(p=><label key={p.id} className="flex items-center gap-3 border-b py-3 text-sm"><input type="checkbox" disabled={busy||p.reserved||["CANCELED","RETURNED","REPLACED"].includes(p.status)} checked={selected.includes(p.id)} onChange={e=>setSelected(e.target.checked?[...selected,p.id]:selected.filter(id=>id!==p.id))}/><span>{p.date} · {money(p.amount)} · {p.reserved?"Agreement already prepared":p.status}</span></label>)}<button disabled={busy||!selected.length} className={button+" mt-4"} onClick={()=>run(()=>prepareReimbursement(a.id,selected),"Agreement prepared for review. Nothing sent or paid.")}>Prepare and preview agreement</button></details>
 </section>;
}
